version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        patterns:
          - "*"
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    groups:
      actions-deps:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
