version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=staging

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:4000"
    environment:
      - NODE_ENV=staging
    env_file:
      - ./backend/.env
