version: "3.9"

services:
  application:
    container_name: application
    build: .
    ports:
      - "4000:4000"
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "cd frontend && yarn install && cd ../backend && yarn install --ignore-engines && cd .. && yarn start-app"
    networks:
      - default
  database:
    container_name: mongo-database
    image: mongo:6.0.4
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'mongo'
      MONGO_INITDB_DATABASE: 'agendazap'
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default: