import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Sidebar } from "@/components/ui/sidebar";
import Header from "./dashboard/presentation/components/Header";
import { Provider } from "@/shared/util/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutprops {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutprops>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex min-h-screen w-full flex-col bg-muted/40">
              <TooltipProvider>
                <Sidebar />
              </TooltipProvider>
              <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
                <Header />
                {children}
              </div>
            </div>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
