name: "DEV DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::294562550042:role/github-actions-agendazap"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "agendazap-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "agendazap-sa-east-1-terraform-lock"
