name: "Release - Staging"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Copy Docker Compose to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            # Install Docker and Docker Compose if not already installed
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo usermod -aG docker ec2-user
            fi

            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Prepare the application directory and set permissions
            mkdir -p ~/app
            chmod 755 ~/app
          EOF

      - name: Check Directory Contents
        run: |
          pwd
          ls -alh

      - name: Upload Docker Compose and Application Files
        run: |
          scp -o StrictHostKeyChecking=no -r ./docker-compose.yaml ./frontend ./backend ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app/

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd ~/app
            sudo docker-compose up -d --build
          EOF
