name: "DEV DEPLOY"

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: production
      aws-assume-role-arn: "arn:aws:iam::294562550042:role/github-actions-agendamais"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "agendamais-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "agendamais-sa-east-1-terraform-lock"
